//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcBlog
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Post
    {
        public int PostId { get; set; }

        [Required(ErrorMessage = "Tên Title không được để trống")]
        [StringLength(50, ErrorMessage = "Tên Title tối đa 50 ký tự")]
        [MinLength(5, ErrorMessage = "Tên Title phải có ít nhất 5 ký tự")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Tên Content không được để trống")]
        [StringLength(500, ErrorMessage = "Tên Title tối đa 500 ký tự")]
        [MinLength(10, ErrorMessage = "Tên Title phải có ít nhất 10 ký tự")]
        public string Content { get; set; }

        [Required(ErrorMessage = "BlogID bắt buộc nhập")]
        [Range(1, int.MaxValue, ErrorMessage = "BlogID phải lớn hơn 0")]
        public int BlogId { get; set; }

        [Required(ErrorMessage = "Ngày tạo bắt buộc nhập")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Blog Blog { get; set; }
    }
}
