//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace MvcBlog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int PostId { get; set; }

        [Required(ErrorMessage = "Nhập tiêu đề")]
        [StringLength(50, ErrorMessage = "Tiêu đề tối đa 50 ký tự")]
        public string Title { get; set; }

        [Display(Name = "Nội dung")]
        [StringLength(500, ErrorMessage = "Nội dung tối đa 500 ký tự")]
        public string Content { get; set; }

        [Required(ErrorMessage = "Phải chọn Blog")]
        public int BlogId { get; set; }
    
        public virtual Blog Blog { get; set; }
    }
}
